# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agid', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=200)),
                ('api_correlation_id', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metro', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(max_length=100)),
                ('requests', models.DecimalField(decimal_places=2, max_digits=20)),
                ('throughput', models.DecimalField(decimal_places=2, max_digits=20)),
                ('peak_throughput', models.DecimalField(decimal_places=2, max_digits=20)),
                ('bandwidth', models.DecimalField(decimal_places=2, max_digits=20)),
                ('peak_bandwidth', models.DecimalField(decimal_places=2, max_digits=20)),
                ('hit_rate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status_4XX', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status_5XX', models.DecimalField(decimal_places=2, max_digits=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkIdentifiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ni', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scid', models.CharField(max_length=50, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('access_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overseas.AccessGroup')),
            ],
        ),
        migrations.AddField(
            model_name='networkidentifiers',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overseas.Service'),
        ),
        migrations.AddField(
            model_name='geo',
            name='ni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overseas.NetworkIdentifiers'),
        ),
    ]
