# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseas', '0004_auto_20160905_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niinfo',
            name='requests',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
