# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseas', '0005_auto_20160905_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='niinfo',
            name='timestamp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
