# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overseas', '0006_niinfo_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='niinfo',
            name='peak_bandwidth',
        ),
        migrations.RemoveField(
            model_name='niinfo',
            name='peak_throughput',
        ),
    ]
