# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseas', '0008_auto_20160909_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invalidations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
                ('force', models.BooleanField(default=False)),
            ],
        ),
    ]
