# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseas', '0009_invalidations'),
    ]

    operations = [
        migrations.AddField(
            model_name='invalidations',
            name='percentComplete',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
