# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseas', '0010_invalidations_percentcomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='invalidations',
            name='time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
