# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overseas', '0012_auto_20160913_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tan14User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_email', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='networkidentifiers',
            name='tan14_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='overseas.Tan14User'),
        ),
    ]
