# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseas', '0014_auto_20160918_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkidentifiers',
            name='cdn',
            field=models.ManyToManyField(blank=True, to='overseas.CDN'),
        ),
    ]
