# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseas', '0015_auto_20160918_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdn',
            name='cdn_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tan14user',
            name='login_email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
