# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overseas', '0016_auto_20160918_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkidentifiers',
            name='cdn',
        ),
        migrations.RemoveField(
            model_name='networkidentifiers',
            name='tan14_user',
        ),
        migrations.AddField(
            model_name='accessgroup',
            name='cdn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='overseas.CDN'),
        ),
        migrations.AddField(
            model_name='cdn',
            name='tan14_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='overseas.Tan14User'),
        ),
    ]
