# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overseas', '0017_auto_20160918_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessgroup',
            name='cdn',
        ),
        migrations.AddField(
            model_name='cdn',
            name='ni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='overseas.NetworkIdentifiers'),
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default='level3', max_length=50),
        ),
    ]
