# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseas', '0019_auto_20160918_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='niinfo',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
