# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseas', '0020_niinfo_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='niinfo',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
