# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseas', '0021_niinfo_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_cn', models.CharField(max_length=100, null=True)),
                ('country_en', models.CharField(max_length=100, null=True)),
                ('country_cn', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='niinfo',
            name='country',
        ),
    ]
