# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overseas', '0022_auto_20161011_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='niinfo',
            name='city_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='overseas.City'),
        ),
    ]
