# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overseas', '0024_remove_niinfo_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='niinfo',
            old_name='city_obj',
            new_name='city',
        ),
    ]
