# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseas', '0025_auto_20161011_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='niinfo',
            name='volume',
            field=models.FloatField(default=0),
        ),
    ]
