# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseas', '0026_niinfo_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niinfo',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
