# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseas', '0027_auto_20161016_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niinfo',
            name='throughput',
            field=models.FloatField(default=0),
        ),
    ]
