# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseas', '0029_auto_20161019_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdn',
            name='cdn_name',
            field=models.CharField(choices=[('level3', 'level3'), ('tan14', 'tan14')], max_length=100),
        ),
    ]
