# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overseas', '0030_auto_20161021_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='tan14user',
            name='active',
            field=models.BooleanField(default=True, verbose_name='是否可用'),
        ),
        migrations.AddField(
            model_name='tan14user',
            name='last_login',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='最后登录时间戳'),
        ),
        migrations.AddField(
            model_name='tan14user',
            name='password',
            field=models.CharField(default=None, max_length=200, verbose_name='密码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tan14user',
            name='record_date',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='注册日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tan14user',
            name='token',
            field=models.CharField(default=None, max_length=200, verbose_name='口令'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cdn',
            name='active',
            field=models.BooleanField(default=True, verbose_name='可用'),
        ),
        migrations.AlterField(
            model_name='cdn',
            name='cdn_name',
            field=models.CharField(choices=[('level3', 'level3'), ('tan14', 'tan14')], max_length=100, verbose_name='CDN'),
        ),
        migrations.AlterField(
            model_name='cdn',
            name='ni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='overseas.NetworkIdentifiers', verbose_name='域名'),
        ),
        migrations.AlterField(
            model_name='tan14user',
            name='login_email',
            field=models.CharField(max_length=100, unique=True, verbose_name='登录邮箱'),
        ),
        migrations.AlterField(
            model_name='tan14user',
            name='operate_right',
            field=models.BooleanField(default=True, verbose_name='是否可刷新、预加载'),
        ),
    ]
