# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-13 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseas', '0031_auto_20161111_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '城市', 'verbose_name_plural': '城市'},
        ),
        migrations.AlterModelOptions(
            name='invalidations',
            options={'verbose_name': '刷新任务', 'verbose_name_plural': '刷新任务'},
        ),
        migrations.AlterModelOptions(
            name='niinfo',
            options={'verbose_name': '信息', 'verbose_name_plural': '信息'},
        ),
        migrations.AlterModelOptions(
            name='tan14user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='tan14user',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='口令'),
        ),
    ]
