# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseas', '0032_auto_20161113_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdn',
            name='tan14_user',
        ),
        migrations.AddField(
            model_name='tan14user',
            name='cdn',
            field=models.ManyToManyField(blank=True, null=True, to='overseas.CDN'),
        ),
        migrations.AlterField(
            model_name='accessgroup',
            name='active',
            field=models.BooleanField(default=True, verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='networkidentifiers',
            name='active',
            field=models.BooleanField(default=True, verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='service',
            name='active',
            field=models.BooleanField(default=True, verbose_name='是否可用'),
        ),
    ]
